./a.out < tests/input1 > output
./a.out < tests/input2 >> output
./a.out < tests/input3 >> output
./a.out < tests/input4 >> output
./a.out < tests/input5 >> output
./a.out < tests/input6 >> output
./a.out < tests/input7 >> output
./a.out < tests/input8 >> output
./a.out < tests/input9 >> output
./a.out < tests/input10 >> output
./a.out < tests/input11 >> output
./a.out < tests/input12 >> output
